class Validate

  def self.capitalize_each string
    string = string.split(' ').map {|w| w.capitalize }.join(' ')
    return string
  end

  def self.check_for_hex_code string
    string.gsub!("&#x2019;", "'")
    string.gsub!("&#x2013;", "-")
    string.gsub!("&#x2018;", "'")
    string.gsub!("&#x2026;", "...")
    string.gsub!("&#x201C;", "\"")
    string.gsub!("&#x201D;", "\"")
    string.gsub!("&#xE0;", "a")
    string.gsub!("&#xE1;", "a")
    string.gsub!("&#xE2;", "a")
    string.gsub!("&#xE3;", "a")
    string.gsub!("&#xE4;", "a")
    string.gsub!("&#xE6;", "ae")
    string.gsub!("&#xE7;", "c")
    string.gsub!("&#xE8;", "e")
    string.gsub!("&#xE9;", "e")
    string.gsub!("&#xEA;", "e")
    string.gsub!("&#xEB;", "e")
    string.gsub!("&#xED;", "i")
    string.gsub!("&#xEE;", "i")
    string.gsub!("&#xEF;", "i")
    string.gsub!("&#xC0;", "A")
    string.gsub!("&#xC1;", "A")
    string.gsub!("&#xC9;", "E")
    string.gsub!("&#xC8;", "E")
    string.gsub!("&#xCA;", "E")
    string.gsub!("&#xD3;", "O")
    string.gsub!("&#xF1;", "n")
    string.gsub!("&#xF2;", "o")
    string.gsub!("&#xF3;", "o")
    string.gsub!("&#xF6;", "o")
    string.gsub!("&#xF8;", "o")
    string.gsub!("&#xF4;", "o")
    string.gsub!("&#xF9;", "u")
    string.gsub!("&#xFA;", "u")
    string.gsub!("&#xFB;", "u")
    string.gsub!("&#xFC;", "u")
    string.gsub!("&#xFD;", "y")

    # invalid multibyte char (US-ASCII)

    #string.gsub!("&#xE0;", "à")
    #string.gsub!("&#xE1;", "á")
    #string.gsub!("&#xE2;", "â")
    #string.gsub!("&#xE3;", "ã")
    #string.gsub!("&#xE4;", "ä")
    #string.gsub!("&#xE6;", "æ")
    #string.gsub!("&#xE7;", "ç")
    #string.gsub!("&#xE8;", "è")
    #string.gsub!("&#xE9;", "é")
    #string.gsub!("&#xEA;", "ê")
    #string.gsub!("&#xEB;", "ë")
    #string.gsub!("&#xED;", "í")
    #string.gsub!("&#xEE;", "î")
    #string.gsub!("&#xEF;", "ï")
    #string.gsub!("&#xC0;", "À")
    #string.gsub!("&#xC1;", "Á")
    #string.gsub!("&#xC9;", "É")
    #string.gsub!("&#xC8;", "È")
    #string.gsub!("&#xCA;", "Ê")
    #string.gsub!("&#xD3;", "Ó")
    #string.gsub!("&#xF1;", "ñ")
    #string.gsub!("&#xF2;", "ò")
    #string.gsub!("&#xF3;", "ó")
    #string.gsub!("&#xF6;", "ö")
    #string.gsub!("&#xF8;", "ø")
    #string.gsub!("&#xF4;", "ô")
    #string.gsub!("&#xF9;", "ù")
    #string.gsub!("&#xFA;", "ú")
    #string.gsub!("&#xFB;", "û")
    #string.gsub!("&#xFC;", "ü")
    #string.gsub!("&#xFD;", "ý")

    return string
  end
end